baseURL = 'https://raileym.github.io/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'anatole'
enableEmoji = true

[params]
title = 'UCKN Blog'
author = 'raileym'
description = 'Promoting better living through small community'
