baseURL = 'https://raileym.github.io/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'anatole'
enableEmoji = true

[params]
title = 'UCKN Blog'
author = 'raileym'
description = 'Better living through daily community'

profilePicture = "images/profile_pic.png"

mainSections = ["blog"]


